### ISSUE TITLE
BMaaS

### ISSUE THREAD

**Issue by codrcodz** [jstraw/mech_tracker#1]
**Issue:** 
I can't use battle mechs as a service!

**Solution:**
Use OpenFaaS to provide a RESTful API that can be used to bootstrap and control the battle from a remote location. Also write some classes that will display ASCII or SVG battle mechs to show battle progress in a Django web UI, and/or on stdout.

**TL;DR:**
Nerd harder.

**Comment by jstraw** [comment]
PR's are welcome, I haven't had time to get back to this and have no idea when I will.
